config/routes.rb
Rails.application.routes.draw do
  root  'roots#index'

  resources :users do
    member do
      get 'subordinate_index'
    end
  end
  get 'users/:id/:period_id' => 'users#show'

  resources :user_sessions

  resources :questions do
    resources :question_alternatives, only:[:new,:create,:edit,:update]
  end
  resources :answers, only:[:create,:update]
  get 'answers/new/:user_id/:period_id' => 'answers#new'
  get 'answers/:answered_user_id/select_period' => 'answers#select_period'
  get 'answers/:answered_user_id/switch_period' => 'answers#switch_period'
  get 'answers/edit/:answered_user_id/:answer_id/:period_id' => 'answers#edit'
  resources :performances
  get 'performances/department/jimu_senmon' => 'performances#jimu_senmon'
  get 'performances/department/kita' => 'performances#kita'
  get 'performances/department/tokyo' => 'performances#tokyo'
  get 'performances/department/honsya' => 'performances#honsya'
  get 'performances/department/shiryo' => 'performances#shiryo'
  get 'performances/department/ishinomaki' => 'performances#ishinomaki'
  get 'performances/department/takasago' => 'performances#takasago'

  resources :performance_rates

  get 'login' => 'user_sessions#new', :as => :login
  # ルート名をloginやlogoutにする
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :question_alternatives, dependent: :destroy
  has_many :answers
  accepts_nested_attributes_for :question_alternatives, allow_destroy: true
  has_many :grade_questions, class_name:
  'GradeQuestion', foreign_key: :question_id
  has_many :grades, through: :grade_questions, dependent: :destroy
  accepts_nested_attributes_for :grade_questions, allow_destroy: true
  validates :text, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    redirect_to users_path, alert: 'アクセス権限がありません' unless current_user.admin?
    @question = Question.new
    5.times {
      @question.question_alternatives.build
    }
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to new_question_path, notice:"質問を登録しました"
    else
      render :new
    end
  end

  def index
    @questions = Question.order("id ASC").page(params[:page]).per(15)
  end

  def edit
    redirect_to users_path, alert: 'アクセス権限がありません' unless current_user.admin?
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(update_question_params)
      redirect_to questions_path, notice: "質問を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path, notice: "質問を消去しました"
  end

  private
  def question_params
    params.require(:question).permit(:text,:weight,{question_alternatives_attributes: [:text,:rate]}, {grade_ids: []})
    # params.require(:モデル名).permit(:カラム名)
  end
  def update_question_params
    params.require(:question).permit(:text,:weight,{question_alternatives_attributes: [:text,:rate, :_destroy, :id]}, {grade_ids: []})
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="divider"></div>
<div class="form">
<%= form_for (@question) ,class: "col s12" do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
       <h4><%= @question.errors.size %> 件のエラーがあります</h4>
      <ul>
      <% @question.errors.full_messages.each  do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class= row>
    <div class="input-field col s8">
      <i class="material-icons prefix">live_help</i>
      <%= f.label :質問項目 %><br>
      <%= f.text_area :text, id: "textarea1", class: "materialize-textarea" %>
    </div>
    <div class="input-field col s4">
      <%= f.label :ウェイト %><br>
      <%= f.select :weight,{"1": 1,"2": 2,"3": 3} %>
    </div>
  </div>

  <!-- 選択肢登録部分 -->
  <%= f.fields_for :question_alternatives do |alternatives_form| %>
    <div class="row">
      <div class="input-field col s8">
        <%= alternatives_form.label :選択肢 %><br>
        <%= alternatives_form.text_field :text, id: "question_alternative", class: "materialize-textarea" %>
      </div>
      <div class="input-field col s4">
        <%= alternatives_form.label :評価尺度 %><br>
        <%= alternatives_form.select :rate,{"0": 0,"1": 1,"2": 2,"3": 3,"4":4} %>
      </div>
    </div>
  <% end %>
    <!-- 選択肢登録部分ここまで -->

    <!-- grade 登録部分 -->
      <div class="question_grade_regist center-align">
        <div class="grade_head row">
          <div class="col s3">
            追加チェック
          </div>
          <div class="col s6">
            部門名
          </div>
          <div class="col s3">
            等級
          </div>
        </div>
      <%= f.collection_check_boxes(:grade_ids, Grade.all, :id, :rank) do |graded| %>
      <div class="row">
        <%= graded.label(class: "/Users/fukuei/projects/pep/vendor/bundle/ruby/2.3.0/gems/materialize-sass-0.100.2/app/assets/stylesheets/materialize/components/forms/_checkboxes.scss */
") do %>
        <div class="col s3">
          <%= graded.check_box(class: "question_grade_regist") %>
        </div>
        <div class="col s6">
          <%= graded.object.department.name %>
        </div>
        <div class="col s3">
          <%= graded.object.rank %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <!-- grade 登録部分ここまで -->

  <div class="actions right-align">
    <%= f.submit "登録" ,:class=>"btn btn-large btn-question waves-effect waves-light" %>
  </div>

<% end %>
</div>

app/views/questions/edit.html.erb
  <div class="page-title">
    <h3>質問項目編集</h3>
  </div>

<%= render 'form' %>

app/views/questions/index.html.erb
  <div class="page-title">
    <h3>質問一覧</h3>
  </div>
  <div class="actions right-align">
  <a href="/questions/new" class="btn-floating question-link waves-effect waves-light"><i class="material-icons">add</i></a>
  </div>
<ul class="pagination">
  <%= paginate @questions %>
</ul>
  <div class="contents row questions-table ">
    <table class="bordered">
      <tbody>
      <% @questions.each do |question|%>
        <tr>
          <td class="questionindex-text">
            <%= link_to "#{question.text}", edit_question_path(question)%>
            &nbsp;&nbsp;
            ウェイト&nbsp;:&nbsp;<%=question.weight %>
          </td>
          <td>
            <%= link_to '消去', question_path(question), method: :delete, data: { confirm: '本当に消去しますか?' } %>
          </td>
        </tr>
      <tr>
        <td colspan="2">
          <% question.grades.each do |grade|%>
            ・<%= grade.department.name %>&nbsp;<%= grade.rank %>&nbsp;等級 <br>
          <% end %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>

<ul class="pagination">
  <%= paginate @questions %>
</ul>

app/views/questions/new.html.erb
<div class="page-title">
  <h3>質問登録</h3>
</div>

<%= render 'form' %>