config/routes.rb
Rails.application.routes.draw do
  root  'roots#index'

  resources :users do
    member do
      get 'subordinate_index'
    end
  end
  get 'users/:id/:period_id' => 'users#show'

  resources :user_sessions

  resources :questions do
    resources :question_alternatives, only:[:new,:create,:edit,:update]
  end
  resources :answers, only:[:create,:update]
  get 'answers/new/:user_id/:period_id' => 'answers#new'
  get 'answers/:answered_user_id/select_period' => 'answers#select_period'
  get 'answers/:answered_user_id/switch_period' => 'answers#switch_period'
  get 'answers/edit/:answered_user_id/:answer_id/:period_id' => 'answers#edit'
  resources :performances
  get 'performances/department/jimu_senmon' => 'performances#jimu_senmon'
  get 'performances/department/kita' => 'performances#kita'
  get 'performances/department/tokyo' => 'performances#tokyo'
  get 'performances/department/honsya' => 'performances#honsya'
  get 'performances/department/shiryo' => 'performances#shiryo'
  get 'performances/department/ishinomaki' => 'performances#ishinomaki'
  get 'performances/department/takasago' => 'performances#takasago'

  resources :performance_rates

  get 'login' => 'user_sessions#new', :as => :login
  # ルート名をloginやlogoutにする
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  skip_before_action :require_login
  def index
  end
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/views/roots/index.html.erb
<!-- <div class="toppage">
  <div class="flash-root">
    <% if notice %>
    <p id="notice-root"><%= flash[:notice]%></p>
    <% elsif alert %>
    <p id="alert-root"><%= flash[:alert]%></p>
    <% end %>
  </div>
  <div class="toppage-contents">
    <% if current_user %>
      <div class="page-title">
        <%= link_to raw("Personel<br/>Evaluation<br/>Program"), users_path %>
      </div>
    <% else %>
      <div class="page-title">
        <%= link_to raw("Personel<br/>Evaluation<br/>Program"), login_path %>
      </div>
    <% end %>
  </div>
</div>
 -->

  <div class="parallax-container" style="height:600px;">
    <div class="parallax"><img src="https://images.pexels.com/photos/5865/healthy-spring-young-green-5865.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
    </div>
  </div>
    <div class="section blue-grey lighten-5">
      <div class="row container">
        <h2 class="header green-text text-darken-1 center-align" style="font-weight: 100" >Fukuei -Personnel evaluation program-</h2>
        <h6 class="gray-text center-align" style="font-weight: 100">福栄肥料株式会社人事評価システム</h6>
        <div class="center-align">
          <%= link_to "ログインする",login_path ,remote: true,:id => "login-btn", :class => "waves-effect waves-light btn",:style => "background-color: #43a047;" "margin-top: 30px;"%>
        </div>
        <div id="login-modal" style="display:none;"></div>
      </div>
    </div>
  <div class="parallax-container" style="height: 600px;">
    <div class="parallax"><img src="https://images.pexels.com/photos/7095/people-coffee-notes-tea.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
    </div>
  </div>