config/routes.rb
Rails.application.routes.draw do
  root  'roots#index'

  resources :users do
    member do
      get 'subordinate_index'
    end
  end
  get 'users/:id/:period_id' => 'users#show'

  resources :user_sessions

  resources :questions do
    resources :question_alternatives, only:[:new,:create,:edit,:update]
  end
  resources :answers, only:[:create,:update]
  get 'answers/new/:user_id/:period_id' => 'answers#new'
  get 'answers/:answered_user_id/select_period' => 'answers#select_period'
  get 'answers/:answered_user_id/switch_period' => 'answers#switch_period'
  get 'answers/edit/:answered_user_id/:answer_id/:period_id' => 'answers#edit'
  resources :performances
  get 'performances/department/jimu_senmon' => 'performances#jimu_senmon'
  get 'performances/department/kita' => 'performances#kita'
  get 'performances/department/tokyo' => 'performances#tokyo'
  get 'performances/department/honsya' => 'performances#honsya'
  get 'performances/department/shiryo' => 'performances#shiryo'
  get 'performances/department/ishinomaki' => 'performances#ishinomaki'
  get 'performances/department/takasago' => 'performances#takasago'

  resources :performance_rates

  get 'login' => 'user_sessions#new', :as => :login
  # ルート名をloginやlogoutにする
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :grade
  has_many :performance_rates
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def index
    @performances = Performance.all
  end
  def jimu_senmon
    jimu_senmon = Department.where("(name = ?) OR (name = ?)", "事務職", "専門職")
    jimu_senmon_grades = []
    jimu_senmon.each do |js|
      jimu_senmon_grades << js.grades
    end
    jimu_senmon_grades.flatten!
    @performances = []
    jimu_senmon_grades.each do |jimu_senmon_grade|
      @performances << jimu_senmon_grade.performances
    end
    @performances.flatten!
  end
  def kita
    kita = Department.find_by(name: "北日本営業")
      kita_grades = kita.grades
    @performances = []
    kita_grades.each do |kita_grade|
      @performances << kita_grade.performances
    end
    @performances.flatten!
  end
  def tokyo
    tokyo = Department.find_by(name: "北日本営業")
      tokyo_grades = tokyo.grades
    @performances = []
    tokyo_grades.each do |tokyo_grade|
      @performances << tokyo_grade.performances
    end
    @performances.flatten!
  end
  def honsya
    honsya = Department.find_by(name: "北日本営業")
      honsya_grades = honsya.grades
    @performances = []
    honsya_grades.each do |honsya_grade|
      @performances << honsya_grade.performances
    end
    @performances.flatten!
  end
  def shiryo
    shiryo = Department.find_by(name: "北日本営業")
      shiryo_grades = shiryo.grades
    @performances = []
    shiryo_grades.each do |shiryo_grade|
      @performances << shiryo_grade.performances
    end
    @performances.flatten!
  end
  def takasago
    takasago_kojo = Department.where("name like '%高砂%'")
    takasago_kojo_grades = []
    takasago_kojo.each do |t|
      takasago_kojo_grades << t.grades
    end
    takasago_kojo_grades.flatten!
    @performances = []
    takasago_kojo_grades.each do |takasago_kojo_grade|
      @performances << takasago_kojo_grade.performances
    end
    @performances.flatten!
  end
  def ishinomaki
    ishinomaki_kojo = Department.where("name like '%石巻%'")
    ishinomaki_kojo_grades = []
    ishinomaki_kojo.each do |t|
      ishinomaki_kojo_grades << t.grades
    end
    ishinomaki_kojo_grades.flatten!
    @performances = []
    ishinomaki_kojo_grades.each do |ishinomaki_kojo_grade|
      @performances << ishinomaki_kojo_grade.performances
    end
    @performances.flatten!
  end
  def new
    @performance = Performance.new
  end
  def create
    @performance = Performance.new(performance_params)
      if @performance.save
        redirect_to new_performance_path, notice:"項目を登録しました"
      else
        render :new
    end
  end
  def edit
    @performance = Performance.find(params[:id])
  end
  def update
    @performance = Performance.find(params[:id])
    if @performance.update(performance_params)
      redirect_to performances_path, notice: "業績評価項目を編集しました"
    else
      render :edit
    end
  end
  def destroy
    @performance = Performance.find(params[:id])
    @performance.destroy
    redirect_to performances_path, notice: "業績評価項目を消去しました"
  end
  private
    def performance_params
      params.require(:performance).permit(:item,:weight,:grade_id)
    end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/_form.html.erb
<div class="divider"></div>
<div class="form">
<%= form_for (@performance) do |f| %>
<div class=row>
  <div class="input-field col s5">
    <%= f.label :業績評価項目 %><br>
    <%= f.text_area :item ,class: "materialize-textarea" %>
  </div>
  <div class="input-field col s3">
    <%= f.label :ウェイト %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="input-field col s4">
    <%= f.label :部署_等級 %><br>
    <%= f.grouped_collection_select(:grade_id, Department.all, :grades, :name, :id, :rank, :prompt => "選択してください") %>
    <!-- f.grouped_collection_select(プロパティ名, オブジェクトの配列, タグを取得するメソッド, タグのラベル, valueの項目, テキストの項目 [, オプション]) -->
  </div>
</div>
<div class="actions right-align">
  <%= f.submit "登録" ,:class=>"btn btn-question waves-effect waves-light" %>
</div>
<% end %>
</div>

app/views/performances/_index.html.erb
<div class="divider"></div>
<div class="form">
  <div class="actions right-align">
    <%= link_to "一覧へ戻る",performances_path,{ :class => "btn question-link waves-effect waves-light" } %>
    <a href="/performances/new" class="btn question-link waves-effect waves-light"><i class="material-icons">add</i></a>
  </div>
  <div class="contents row questions-table ">
      <table class="bordered highlight">
        <tbody>
        <% @performances.each do |performance|%>
          <tr>
            <td class="questionindex-text">
              <%= link_to "#{performance.item}", edit_performance_path(performance)%>
            </td>
            <td>
              ウェイト&nbsp;:&nbsp;<%=performance.weight %>
            </td>
            <td>
              <%= performance.grade.department.name%>
              <%= performance.grade.rank %>等級
            </td>
            <td>
              <%= link_to '消去', performance_path(performance), method: :delete, data: { confirm: '本当に消去しますか?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/performances/edit.html.erb
<div class="page-title">
  <h3>業績評価項目編集</h3>
</div>


<%= render 'form' %>

app/views/performances/honsya.html.erb
<div class="page-title">
  <h3>業績評価(本社)</h3>
</div>

<%= render 'index' %>

app/views/performances/index.html.erb
<div class="page-title">
  <h3>業績評価一覧</h3>
</div>
<div class="divider"></div>
<div class="form">
<div class="actions right-align">
  <%= link_to "高砂", 'performances/department/takasago' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <%= link_to "石巻", 'performances/department/ishinomaki' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <%= link_to "飼料", 'performances/department/shiryo' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <%= link_to "本社", 'performances/department/honsya' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <%= link_to "東京", 'performances/department/tokyo' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <%= link_to "北日本", 'performances/department/kita' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <%= link_to "事務・専門職", 'performances/department/jimu_senmon' ,{ :class => "btn question-link waves-effect waves-light" } %>
  <a href="/performances/new" class="btn question-link waves-effect waves-light"><i class="material-icons">add</i></a>

</div>
<div class="contents row questions-table ">
    <table class="bordered highlight">
      <tbody>
      <% @performances.each do |performance|%>
        <tr>
          <td class="questionindex-text">
            <%= link_to "#{performance.item}", edit_performance_path(performance)%>
          </td>
          <td>
            ウェイト&nbsp;:&nbsp;<%=performance.weight %>
          </td>
          <td>
            <%= performance.grade.department.name%>
            <%= performance.grade.rank %>等級
          </td>
          <td>
            <%= link_to '消去', performance_path(performance), method: :delete, data: { confirm: '本当に消去しますか?' } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/performances/ishinomaki.html.erb
<div class="page-title">
  <h3>業績評価(石巻)</h3>
</div>

<%= render 'index' %>

app/views/performances/jimu_senmon.html.erb
<div class="page-title">
  <h3>業績評価(事務・専門職)</h3>
</div>
<%= render 'index' %>

app/views/performances/kita.html.erb
<div class="page-title">
  <h3>業績評価(北日本)</h3>
</div>

<%= render 'index' %>

app/views/performances/new.html.erb
<div class="page-title">
  <h3>業績評価項目登録</h3>
</div>


<%= render 'form' %>

app/views/performances/shiryo.html.erb
<div class="page-title">
  <h3>業績評価(飼料部)</h3>
</div>

<%= render 'index' %>

app/views/performances/takasago.html.erb
<div class="page-title">
  <h3>業績評価(高砂)</h3>
</div>

<%= render 'index' %>

app/views/performances/tokyo.html.erb
<div class="page-title">
  <h3>業績評価(東京)</h3>
</div>

<%= render 'index' %>