config/routes.rb
Rails.application.routes.draw do
  root  'roots#index'

  resources :users do
    member do
      get 'subordinate_index'
    end
  end
  get 'users/:id/:period_id' => 'users#show'

  resources :user_sessions

  resources :questions do
    resources :question_alternatives, only:[:new,:create,:edit,:update]
  end
  resources :answers, only:[:create,:update]
  get 'answers/new/:user_id/:period_id' => 'answers#new'
  get 'answers/:answered_user_id/select_period' => 'answers#select_period'
  get 'answers/:answered_user_id/switch_period' => 'answers#switch_period'
  get 'answers/edit/:answered_user_id/:answer_id/:period_id' => 'answers#edit'
  resources :performances
  get 'performances/department/jimu_senmon' => 'performances#jimu_senmon'
  get 'performances/department/kita' => 'performances#kita'
  get 'performances/department/tokyo' => 'performances#tokyo'
  get 'performances/department/honsya' => 'performances#honsya'
  get 'performances/department/shiryo' => 'performances#shiryo'
  get 'performances/department/ishinomaki' => 'performances#ishinomaki'
  get 'performances/department/takasago' => 'performances#takasago'

  resources :performance_rates

  get 'login' => 'user_sessions#new', :as => :login
  # ルート名をloginやlogoutにする
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :answering_user, class_name: 'User', foreign_key: :answering_user_id
  belongs_to :answered_user, class_name: 'User', foreign_key: :answered_user_id
  belongs_to :period
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :grades
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  has_many :users
  has_many :questions, through: :grade_questions
  belongs_to :department
  has_many :grade_questions, class_name: 'GradeQuestion', foreign_key: :grade_id
  has_many :performances
end

app/models/grade_question.rb
class GradeQuestion < ActiveRecord::Base
  belongs_to :grade
  belongs_to :question
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :grade
  has_many :performance_rates
end

app/models/performance_rate.rb
class PerformanceRate < ActiveRecord::Base
  belongs_to :performance
  belongs_to :period
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :answers
  has_many :performance_rates
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :question_alternatives, dependent: :destroy
  has_many :answers
  accepts_nested_attributes_for :question_alternatives, allow_destroy: true
  has_many :grade_questions, class_name:
  'GradeQuestion', foreign_key: :question_id
  has_many :grades, through: :grade_questions, dependent: :destroy
  accepts_nested_attributes_for :grade_questions, allow_destroy: true
  validates :text, presence: true
end

app/models/question_alternative.rb
class QuestionAlternative < ActiveRecord::Base
  belongs_to :question

  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :password, length: {minimum: 6}
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :name, uniqueness: true, presence: true
  validates :superior_id, numericality: true, allow_blank: true
  enum role: {
    normal: 0,  #係長まで
    manager: 1,  #課長・次長
    executive: 2,  #部長・支店長・工場長
    admin: 3  #管理者
  }

# アソシエーション（自己結合関連付け）
  has_many :subordinate_users, class_name: 'User', foreign_key: :superior_id
  belongs_to :superior_user, class_name: 'User', foreign_key: :superior_id

  has_many :answering_answers, class_name: 'Answer', foreign_key: :answering_user_id
  has_many :answered_answer, class_name: 'Answer', foreign_key: :answered_user_id

  belongs_to :grade
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  skip_before_action :require_login
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/matelpage_helper.rb
module MatelpageHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fukuei-Personnel evaluation program-</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src='https://code.jquery.com/jquery-2.1.4.js'></script>
    <%= favicon_link_tag() %>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGjDT8Us6vibhEvOAz0HQg2K5WfDS1JRg"></script> -->
  </head>

  <body>
      <header>
        <nav>
          <div class="nav-wrapper left-align">
            <ul id="dropdown1" class="dropdown-content">
              <% if current_user && current_user.executive? %>
                <li><%= link_to "部下一覧", subordinate_index_user_path(current_user.id) %></li>
                  <li><%= link_to '自己評価', "/answers/#{current_user.id}/select_period" %></li>
                <% if current_user.answered_answer.present? %>
                <% end %>

              <% elsif current_user && current_user.manager? %>
                <li><%= link_to "部下一覧", subordinate_index_user_path(current_user) %></li>
                <li><%= link_to '自己評価', "/answers/#{current_user.id}/select_period" %></li>

              <% elsif current_user && current_user.admin? %>
                <li><%= link_to "質問一覧", questions_path %></li>
                <li><%= link_to '自己評価', "/answers/#{current_user.id}/select_period" %></li>

              <% elsif current_user && current_user.normal? %>
                  <li><%= link_to '評価・閲覧', "/answers/#{current_user.id}/select_period" %></li>
                <% if current_user.answering_answers.present? %>
                <% end %>
              <% end %>
            </ul>

                <a href="<%= users_path %>" class="brand-logo left-logo left-align"><img class="brand-logo" src="../../../assets/fukuei_logo.png" alt="fukuei"></a>

              <ul class="right">
                <% if current_user %>
                   <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons">menu</i></a></li>
                <% end %>
                <% if current_user %>
                  <li><%= link_to "ログアウト", :logout , method: :post %></li>
                  <li><%= link_to "#{current_user.name}", edit_user_path(current_user) %></li>
                <% end %>
              </ul>
          </div>
        </nav>
      </header>
      <div class="contents">
        <% unless controller.controller_name == "roots" && controller.action_name == "index" %>
          <div class="container">
        <% end %>
        <% unless controller.controller_name == "roots" && controller.action_name == "index" %>
          <div class="flash_message center-align z-depth-1">
          <% if notice %>
            <p id="notice"><%= flash[:notice]%></p>
          <% elsif alert %>
            <p id="alert"><%= flash[:alert]%></p>
        <% end %>
          </div>
        <% end %>
        <%= yield %>
          </div>
      </div>
<!--       <footer class="page-footer">
        © 2018 Copyright K.yuki All Rights Reserved.
      </footer> -->
    <%= javascript_include_tag 'application'%>
  </body>
</html>